{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "43d9abcd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting hydrafloods\n",
      "  Using cached hydrafloods-2021.10.11-py3-none-any.whl (85 kB)\n",
      "Collecting simplecmr\n",
      "  Using cached simplecmr-0.0.1-py3-none-any.whl (6.9 kB)\n",
      "Collecting gcsfs\n",
      "  Using cached gcsfs-2022.2.0-py2.py3-none-any.whl (24 kB)\n",
      "Collecting earthengine-api\n",
      "  Using cached earthengine-api-0.1.301.tar.gz (236 kB)\n",
      "Collecting fire\n",
      "  Using cached fire-0.4.0.tar.gz (87 kB)\n",
      "Collecting pipetools\n",
      "  Using cached pipetools-1.1.0.tar.gz (16 kB)\n",
      "Requirement already satisfied: future in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api->hydrafloods) (0.18.2)\n",
      "Collecting google-cloud-storage\n",
      "  Using cached google_cloud_storage-2.1.0-py2.py3-none-any.whl (106 kB)\n",
      "Collecting google-api-python-client<2,>=1.12.1\n",
      "  Using cached google_api_python_client-1.12.10-py2.py3-none-any.whl (61 kB)\n",
      "Requirement already satisfied: google-auth>=1.4.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api->hydrafloods) (2.6.0)\n",
      "Collecting google-auth-httplib2>=0.0.3\n",
      "  Using cached google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)\n",
      "Collecting httplib2<1dev,>=0.9.2\n",
      "  Using cached httplib2-0.20.4-py3-none-any.whl (96 kB)\n",
      "Collecting httplib2shim\n",
      "  Using cached httplib2shim-0.0.3.tar.gz (17 kB)\n",
      "Requirement already satisfied: six in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api->hydrafloods) (1.15.0)\n",
      "Collecting google-api-core<3dev,>=1.21.0\n",
      "  Using cached google_api_core-2.7.0-py3-none-any.whl (114 kB)\n",
      "Collecting uritemplate<4dev,>=3.0.0\n",
      "  Using cached uritemplate-3.0.1-py2.py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (3.19.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (2.25.1)\n",
      "Collecting googleapis-common-protos<2.0dev,>=1.52.0\n",
      "  Using cached googleapis_common_protos-1.55.0-py2.py3-none-any.whl (212 kB)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api->hydrafloods) (5.0.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api->hydrafloods) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api->hydrafloods) (4.8)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from httplib2<1dev,>=0.9.2->earthengine-api->hydrafloods) (2.4.7)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api->hydrafloods) (0.4.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (1.26.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (2021.10.8)\n",
      "Requirement already satisfied: idna<3,>=2.5 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (2.10)\n",
      "Requirement already satisfied: chardet<5,>=3.0.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api->hydrafloods) (4.0.0)\n",
      "Requirement already satisfied: termcolor in c:\\users\\user\\anaconda3\\lib\\site-packages (from fire->hydrafloods) (1.1.0)\n",
      "Requirement already satisfied: decorator>4.1.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from gcsfs->hydrafloods) (5.0.6)\n",
      "Requirement already satisfied: google-auth-oauthlib in c:\\users\\user\\anaconda3\\lib\\site-packages (from gcsfs->hydrafloods) (0.4.6)\n",
      "Collecting aiohttp<4\n",
      "  Using cached aiohttp-3.8.1-cp38-cp38-win_amd64.whl (555 kB)\n",
      "Collecting fsspec==2022.02.0\n",
      "  Using cached fsspec-2022.2.0-py3-none-any.whl (134 kB)\n",
      "Collecting multidict<7.0,>=4.5\n",
      "  Downloading multidict-6.0.2-cp38-cp38-win_amd64.whl (28 kB)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from aiohttp<4->gcsfs->hydrafloods) (20.3.0)\n",
      "Collecting charset-normalizer<3.0,>=2.0\n",
      "  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)\n",
      "Collecting aiosignal>=1.1.2\n",
      "  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)\n",
      "Collecting async-timeout<5.0,>=4.0.0a3\n",
      "  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)\n",
      "Collecting yarl<2.0,>=1.0\n",
      "  Downloading yarl-1.7.2-cp38-cp38-win_amd64.whl (122 kB)\n",
      "Collecting frozenlist>=1.1.1\n",
      "  Downloading frozenlist-1.3.0-cp38-cp38-win_amd64.whl (33 kB)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth-oauthlib->gcsfs->hydrafloods) (1.3.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs->hydrafloods) (3.1.1)\n",
      "Collecting google-cloud-core<3.0dev,>=1.6.0\n",
      "  Using cached google_cloud_core-2.2.3-py2.py3-none-any.whl (29 kB)\n",
      "Collecting google-resumable-media>=1.3.0\n",
      "  Using cached google_resumable_media-2.3.2-py2.py3-none-any.whl (76 kB)\n",
      "Collecting google-crc32c<2.0dev,>=1.0\n",
      "  Downloading google_crc32c-1.3.0-cp38-cp38-win_amd64.whl (27 kB)\n",
      "Requirement already satisfied: setuptools>=0.6b1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pipetools->hydrafloods) (52.0.0.post20210125)\n",
      "Collecting requests-cache\n",
      "  Using cached requests_cache-0.9.3-py3-none-any.whl (47 kB)\n",
      "Collecting url-normalize<2.0,>=1.4\n",
      "  Using cached url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)\n",
      "Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests-cache->simplecmr->hydrafloods) (1.4.4)\n",
      "Collecting cattrs<2.0,>=1.8\n",
      "  Using cached cattrs-1.10.0-py3-none-any.whl (29 kB)\n",
      "Collecting attrs>=17.3.0\n",
      "  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)\n",
      "Building wheels for collected packages: earthengine-api, fire, httplib2shim, pipetools\n",
      "  Building wheel for earthengine-api (setup.py): started\n",
      "  Building wheel for earthengine-api (setup.py): finished with status 'done'\n",
      "  Created wheel for earthengine-api: filename=earthengine_api-0.1.301-py3-none-any.whl size=265508 sha256=74da7f1f77f9d70f7101645e3b6736f663f9d4880f4171ca4c8f3f954b570b27\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\72\\3c\\47\\2fe37c97a913fb3a84dab65e7b78912b72ceefb13e565153c9\n",
      "  Building wheel for fire (setup.py): started\n",
      "  Building wheel for fire (setup.py): finished with status 'done'\n",
      "  Created wheel for fire: filename=fire-0.4.0-py2.py3-none-any.whl size=115928 sha256=e68c326945c28890c9e5eae4d21e45ea4647a4befae6253e445357151715d6ed\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\1f\\10\\06\\2a990ee4d73a8479fe2922445e8a876d38cfbfed052284c6a1\n",
      "  Building wheel for httplib2shim (setup.py): started\n",
      "  Building wheel for httplib2shim (setup.py): finished with status 'done'\n",
      "  Created wheel for httplib2shim: filename=httplib2shim-0.0.3-py2.py3-none-any.whl size=18059 sha256=78563bdba87c4061dc3db99c233c08293bdc863e0dd4d55e5174c94f33b86d60\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\04\\5d\\b9\\a746c136fae5811cb2d30d8112b0f72ba40e24d22885bbe7c7\n",
      "  Building wheel for pipetools (setup.py): started\n",
      "  Building wheel for pipetools (setup.py): finished with status 'done'\n",
      "  Created wheel for pipetools: filename=pipetools-1.1.0-py3-none-any.whl size=13604 sha256=50e0b6e859391e3330092d887ea27f27fbaf59ffb855f2f16c9574f78c20758c\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\49\\68\\15\\044c9c0e6b387e9cbadb688c5366433cd4f233214c812ec285\n",
      "Successfully built earthengine-api fire httplib2shim pipetools\n",
      "Installing collected packages: googleapis-common-protos, multidict, httplib2, google-crc32c, google-api-core, frozenlist, attrs, yarl, url-normalize, uritemplate, google-resumable-media, google-cloud-core, google-auth-httplib2, charset-normalizer, cattrs, async-timeout, aiosignal, requests-cache, httplib2shim, google-cloud-storage, google-api-python-client, fsspec, aiohttp, simplecmr, pipetools, gcsfs, fire, earthengine-api, hydrafloods\n",
      "  Attempting uninstall: attrs\n",
      "    Found existing installation: attrs 20.3.0\n",
      "    Uninstalling attrs-20.3.0:\n",
      "      Successfully uninstalled attrs-20.3.0\n",
      "  Attempting uninstall: fsspec\n",
      "    Found existing installation: fsspec 0.9.0\n",
      "    Uninstalling fsspec-0.9.0:\n",
      "      Successfully uninstalled fsspec-0.9.0\n",
      "Successfully installed aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 cattrs-1.10.0 charset-normalizer-2.0.12 earthengine-api-0.1.301 fire-0.4.0 frozenlist-1.3.0 fsspec-2022.2.0 gcsfs-2022.2.0 google-api-core-2.7.0 google-api-python-client-1.12.10 google-auth-httplib2-0.1.0 google-cloud-core-2.2.3 google-cloud-storage-2.1.0 google-crc32c-1.3.0 google-resumable-media-2.3.2 googleapis-common-protos-1.55.0 httplib2-0.20.4 httplib2shim-0.0.3 hydrafloods-2021.10.11 multidict-6.0.2 pipetools-1.1.0 requests-cache-0.9.3 simplecmr-0.0.1 uritemplate-3.0.1 url-normalize-1.4.3 yarl-1.7.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install hydrafloods"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "17f87eda",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: earthengine-api in c:\\users\\user\\anaconda3\\lib\\site-packages (0.1.301)\n",
      "Requirement already satisfied: google-cloud-storage in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (2.1.0)\n",
      "Requirement already satisfied: future in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (0.18.2)\n",
      "Requirement already satisfied: six in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (1.15.0)\n",
      "Requirement already satisfied: httplib2shim in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (0.0.3)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.0.3 in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (0.1.0)\n",
      "Requirement already satisfied: google-api-python-client<2,>=1.12.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (1.12.10)\n",
      "Requirement already satisfied: google-auth>=1.4.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (2.6.0)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.9.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from earthengine-api) (0.20.4)\n",
      "Requirement already satisfied: uritemplate<4dev,>=3.0.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-python-client<2,>=1.12.1->earthengine-api) (3.0.1)\n",
      "Requirement already satisfied: google-api-core<3dev,>=1.21.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-python-client<2,>=1.12.1->earthengine-api) (2.7.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (1.55.0)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (3.19.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (2.25.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (4.8)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (0.2.8)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-auth>=1.4.1->earthengine-api) (5.0.0)\n",
      "Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from httplib2<1dev,>=0.9.2->earthengine-api) (2.4.7)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.4.1->earthengine-api) (0.4.8)\n",
      "Requirement already satisfied: idna<3,>=2.5 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (2.10)\n",
      "Requirement already satisfied: chardet<5,>=3.0.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (4.0.0)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (1.26.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<3dev,>=1.21.0->google-api-python-client<2,>=1.12.1->earthengine-api) (2021.10.8)\n",
      "Requirement already satisfied: google-resumable-media>=1.3.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-cloud-storage->earthengine-api) (2.3.2)\n",
      "Requirement already satisfied: google-cloud-core<3.0dev,>=1.6.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-cloud-storage->earthengine-api) (2.2.3)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from google-resumable-media>=1.3.0->google-cloud-storage->earthengine-api) (1.3.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install earthengine-api"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "22d50393",
   "metadata": {},
   "outputs": [],
   "source": [
    "import ee"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "34926a41",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<p>To authorize access needed by Earth Engine, open the following\n",
       "        URL in a web browser and follow the instructions:</p>\n",
       "        <p><a href=https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&code_challenge=Kz71UPamYwx7K8yYZ9TkB4EgkGKwmbA-9TZIxwwy2uE&code_challenge_method=S256>https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&code_challenge=Kz71UPamYwx7K8yYZ9TkB4EgkGKwmbA-9TZIxwwy2uE&code_challenge_method=S256</a></p>\n",
       "        <p>The authorization workflow will generate a code, which you\n",
       "        should paste in the box below</p>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter verification code: 4/1AX4XfWiDAaUDqkFG_qheT28Ejs_Iu8hIlplI7r-OaVkXU1VNXFWTtmyfXWg\n",
      "\n",
      "Successfully saved authorization token.\n"
     ]
    }
   ],
   "source": [
    "ee.Authenticate()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "15a878d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "ee.Initialize()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "7c0de9f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import the hydrafloods and ee package\n",
    "import hydrafloods as hf\n",
    "import ee"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "4c40365a",
   "metadata": {},
   "outputs": [],
   "source": [
    "start_time = \"2019-10-05\"\n",
    "end_time =  \"2019-10-06\"\n",
    "region = ee.Geometry.Rectangle([104, 11.5, 106, 12.5])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "534de67e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# get the Sentinel-1 collection\n",
    "# the hf.dataset classes performs the spatial-temporal filtering for you\n",
    "s1 = hf.datasets.Sentinel1(region, start_time, end_time)\n",
    "\n",
    "# apply a water mapping function to the S1 dataset\n",
    "# this applies the \"Edge Otsu\" algorithm from https://doi.org/10.3390/rs12152469\n",
    "water_imgs = s1.apply_func(\n",
    "    hf.thresholding.edge_otsu,\n",
    "    initial_threshold=-14,\n",
    "    thresh_no_data=-20,\n",
    "    edge_buffer=300\n",
    ")\n",
    "\n",
    "# take the mode from multiple images\n",
    "# since this is just imagery from one day, it will simply mosaic the images\n",
    "water_map = ee.Image(water_imgs.collection.mode())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "90897d40",
   "metadata": {},
   "outputs": [],
   "source": [
    "# export the water map\n",
    "hf.geeutils.export_image(\n",
    "    water_map,\n",
    "    region,\n",
    "    'users/hamzahhamizan18/water_map_example',\n",
    "    scale=30,\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8d67f62d",
   "metadata": {},
   "source": [
    "==============================================================="
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "93ed370e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting up42-py\n",
      "  Using cached up42_py-0.20.0-py3-none-any.whl (50 kB)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (3.3.4)\n",
      "Requirement already satisfied: requests-oauthlib in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (1.3.0)\n",
      "Collecting rasterio\n",
      "  Using cached rasterio-1.2.10.tar.gz (2.3 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.9.tar.gz (2.3 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.8.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.7.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.6.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.5.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.4.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.3.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.2.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.1.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.2.0.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.8.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.7.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.6.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.5.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.4.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.3.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.2.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.1.tar.gz (2.2 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.1.0.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.0.28.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.0.27.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.0.26.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.0.25.tar.gz (2.1 MB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'error'\n",
      "  Downloading rasterio-1.0.24.tar.gz (1.9 MB)\n",
      "  Downloading rasterio-1.0.23.tar.gz (1.9 MB)\n",
      "  Downloading rasterio-1.0.22.tar.gz (1.9 MB)\n",
      "  Downloading rasterio-1.0.21.tar.gz (1.9 MB)\n",
      "  Downloading rasterio-1.0.20.tar.gz (1.9 MB)\n",
      "  Downloading rasterio-1.0.18.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.17.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.16.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.15.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.14.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.13.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.12.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.11.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.10.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.9.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.8.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.7.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.6.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.5.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.4.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.3.post1.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.3.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.2.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.1.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-1.0.0.tar.gz (1.8 MB)\n",
      "  Downloading rasterio-0.36.0.tar.gz (1.2 MB)\n",
      "Requirement already satisfied: tqdm in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (4.59.0)\n",
      "Collecting folium\n",
      "  Downloading folium-0.12.1.post1-py2.py3-none-any.whl (95 kB)\n",
      "Note: you may need to restart the kernel to use updated packages.Collecting branca\n",
      "  Downloading branca-0.4.2-py3-none-any.whl (24 kB)\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmptfa336pn'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_7883bda369dc432e9aec2f914dc6046a\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/44/5e/9f19e1e6fe980b59d8da8809f2e8f81eb7f0322c71914f077edcbcd9a110/rasterio-1.2.10.tar.gz#sha256=6062456047ba6494fe18bd0da98a383b6fad5306b16cd52a22e76c59172a2b5f (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmptfa336pn' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpu9n_kq9r'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_dbdc2f89bd984a6a95b9784c8486b6fd\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1f/70/4e7a789f4988955e4c381de80923e184f912683bbe6fc4a3a00c91efdf59/rasterio-1.2.9.tar.gz#sha256=012a4964d8db365be4fae0af9cbeba00e683e5904d5031e8ba42ccb6040cc887 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpu9n_kq9r' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmphquaxjtd'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_17d9362e6a7940708677f0bb06ef1024\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/5a/64/91fcf8482d5c380b68b4f69d5b0c75785db038b6923481b8e53234cf826f/rasterio-1.2.8.tar.gz#sha256=8196b7a71fea3c1573dd48d9ab0e78955e1d26e81848cce318c4930bd96782fe (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmphquaxjtd' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6xyf9gl0'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_01a30717a5a242f1b0522b4b1c5aca75\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/bd/14/9dae549c8425c7f4d0819eb770875f813d46e97b3d75d5bbaeed22630f6a/rasterio-1.2.7.tar.gz#sha256=f97d688fd8bdf02a2d3c79fded6ba7409a62564fa59ddb43f8069c1b2610ee4f (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6xyf9gl0' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp00cssy81'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_52938560cbe7441db4fe422ec8253cff\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d6/61/f083df6539a3ad5ddb480dd5551d55039b9f59948c68415a9737ea62081a/rasterio-1.2.6.tar.gz#sha256=24975b97fe2fc3fd282d59640baab19de431448e1b23be6b85b68fecc1362f88 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp00cssy81' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpbqz9obpf'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_d0b050c28ef84b29b8ab9d077186f726\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/5c/a3/2f30c89323826cba9344b55d3355df16695dff14aa312dbddb8050bb571f/rasterio-1.2.5.tar.gz#sha256=dbf85c2c3dbdc5000cb0afc24bd7625ff696bd8698661fed23d115164333d80f (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpbqz9obpf' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp4zaue66q'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_5aca915021504369b0e82b842d508f7d\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/64/22/a8a0d384147fcbb2ecdea0a05d7d178e8692c62659fe733bd4b3966e6e95/rasterio-1.2.4.tar.gz#sha256=31248c5ddc8f138f73b166dd93384aa72d11abd0dc27dca90a190276c7976aa3 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp4zaue66q' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6ku_rqz_'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_b69d87adb4ed47d1843e070fcad54503\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/97/85/3591f1b04fc9e9038aff7d6c5ddc816e8a7c0c8362f69b70ed6455ebcebd/rasterio-1.2.3.tar.gz#sha256=d8c345e01052b70ac3bbbe100c83def813c0ab19f7412c2c98e553d03720c1c5 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6ku_rqz_' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6kjp12a1'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_a22111462a654569baf347fe9d62c5be\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b3/e9/f7092cd8ac97f1b2a6f15bfc084b496d40653dd188dd0945cfe1bbd67abe/rasterio-1.2.2.tar.gz#sha256=8187d01f30d4e01e93f0a434df6a4cc63dd026a18b5287c242b066cb56223424 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp6kjp12a1' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpgi797gry'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_c6a1a29c2c784057a80485aaf1c22a57\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/cf/15/79f2ed3d25b02ace4c3a07168ef4a3ff34afc86537d118fd25230df6830f/rasterio-1.2.1.tar.gz#sha256=81d4181514c67dc660d7b8cf943ad55c4fb3e0a17ac893d92628ac928cfab3d8 (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpgi797gry' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_cpz4zsj'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_fb209eb04cf84c5ea5c9566d73146c42\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b9/bc/3bcf9fb9139112e389a4c8b914c45dac01981db211d18dae7af5a081c781/rasterio-1.2.0.tar.gz#sha256=d1c70ae16f4048dce8292a607f016833c024c941b3eca51cd773fc494172c6eb (from https://pypi.org/simple/rasterio/) (requires-python:>=3.6). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_cpz4zsj' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpj7x8uns6'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_8c2d060bd2744fba9330fc9b0db9715b\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/73/2d/3e1bc56d75bf7c4cd5df51536992b3420197f2aa5ddd4d93e12100715dff/rasterio-1.1.8.tar.gz#sha256=f7cac7e2ecf65b4b1eb78c994c63bd429b67dc679b0bc0ecfe487d3d5bf88fd5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpj7x8uns6' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpcc152uom'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_1dac254bcdb24dba9470da85b51d98e9\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/50/bf/35e564093d84509406c3d96e147132067ddbc591966b9b52c3aa0331f1b8/rasterio-1.1.7.tar.gz#sha256=8418c024f9bf7350d03855039d2700064532bae33a3c6ee885c8b6c8fc13415a (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpcc152uom' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpwzpws4j_'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_cfb5d43d0b5f49bab7a4069329044f50\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/c0/e0/a055775339c04db97a92254b08d70a796ff0cc8b4c9a23f92daa1dc96612/rasterio-1.1.6.tar.gz#sha256=c098881dfe301c5e3aa43a3171985fb365d64dc4d1c0a1d8288c7870fb240efe (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpwzpws4j_' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpt_3329f7'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_8fceea7b2b6e42aeb48b1cb4dd9743d4\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/86/43/aae52a19a69ee30d28d0374c5f22d473ba3ba98ace4a5a5330a26590df95/rasterio-1.1.5.tar.gz#sha256=ebe75c71f9257c780615caaec8ef81fa4602702cf9290a65c213e1639284acc9 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpt_3329f7' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpwqa0o5n1'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_62318ac2b78f4fee87422b9608110e79\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/3a/61/c91a2faa4e7bd1b3ec915d8cb9fb6cf16fe5b85e967c0336c9f0ec837ca0/rasterio-1.1.4.tar.gz#sha256=5d7393f3a690a91813022452022df1d5a3a2c732019f24f2bd0b051fd47a03c1 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpwqa0o5n1' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpo9roqtqy'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_853f00ec8a1a4a809c80b9afd588882b\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d2/8a/8a7c67e75092cea6de3347db5e9e65011def24da8e632a0dd74253733d5a/rasterio-1.1.3.tar.gz#sha256=fe2eac942ae4f8a97246c8cd3977723997817b53a9058cf1959551026c6177e7 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpo9roqtqy' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpga3cx517'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_fbf5e04d9c034e6b9cb35efb12ba5597\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/06/f1/dd83f3ad863a98ac543e19abd485bce1ba7e545c79a64cc186668fa49aa9/rasterio-1.1.2.tar.gz#sha256=f6df894e37eefb408e4562ab9c14efcf027b0f5f279be5ff8b2105d03f2d3c37 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpga3cx517' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpb63e9s3b'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_207ecd0235b743e68fa7aa76b2a5beea\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9b/f1/c178b41a94ab6bfb4d64a224092d7549a5b8618ce21ae644e203f56a0efa/rasterio-1.1.1.tar.gz#sha256=7571ff5b96aeb9b1ac83d56534895c0e3d5e8678568375cf83c87111e2856fcb (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpb63e9s3b' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_3h50b5d'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_94219c167956491f9f392b286ba3c62f\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting descartes\n",
      "  Using cached descartes-1.1.0-py3-none-any.whl (5.8 kB)\n",
      "Requirement already satisfied: click in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (7.1.2)\n",
      "Requirement already satisfied: requests in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (2.25.1)\n",
      "Requirement already satisfied: tenacity in c:\\users\\user\\anaconda3\\lib\\site-packages (from up42-py) (8.0.1)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)\n",
      "Collecting geojson\n",
      "  Downloading geojson-2.5.0-py2.py3-none-any.whl (14 kB)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from branca->up42-py) (2.11.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\user\\anaconda3\\lib\\site-packages (from folium->up42-py) (1.20.1)\n",
      "Requirement already satisfied: MarkupSafe>=0.23 in c:\\users\\user\\anaconda3\\lib\\site-packages (from jinja2->branca->up42-py) (1.1.1)\n",
      "Collecting fiona>=1.8\n",
      "  Downloading Fiona-1.8.21.tar.gz (1.0 MB)\n",
      "  Downloading Fiona-1.8.20.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.19.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.18.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.17.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.16.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.15.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.14.tar.gz (1.3 MB)\n",
      "  Downloading Fiona-1.8.13.post1.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.13.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.12.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.11.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.10.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.9.post2.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.9.post1.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.9.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.8.tar.gz (1.7 MB)\n",
      "  Downloading Fiona-1.8.7.tar.gz (1.7 MB)\n",
      "  Downloading Fiona-1.8.6.tar.gz (1.7 MB)\n",
      "  Downloading Fiona-1.8.5.tar.gz (1.7 MB)\n",
      "  Downloading Fiona-1.8.4.tar.gz (1.1 MB)\n",
      "  Downloading Fiona-1.8.3.tar.gz (1.1 MB)\n",
      "  Downloading Fiona-1.8.2.tar.gz (1.2 MB)\n",
      "  Downloading Fiona-1.8.1.tar.gz (1.1 MB)\n",
      "  Downloading Fiona-1.8.0.tar.gz (1.4 MB)\n",
      "Collecting geopandas\n",
      "  Downloading geopandas-0.10.1-py2.py3-none-any.whl (1.0 MB)\n",
      "  Downloading geopandas-0.10.0-py2.py3-none-any.whl (1.0 MB)\n",
      "  Downloading geopandas-0.9.0-py2.py3-none-any.whl (994 kB)\n",
      "  Downloading geopandas-0.8.2-py2.py3-none-any.whl (962 kB)\n",
      "Collecting shapely\n",
      "  Downloading Shapely-1.8.1.post1-cp38-cp38-win_amd64.whl (1.3 MB)\n",
      "Collecting pyproj>=2.2.0\n",
      "  Downloading pyproj-3.3.0-cp38-cp38-win_amd64.whl (6.3 MB)\n",
      "Collecting fiona\n",
      "  Downloading Fiona-1.7.13.tar.gz (731 kB)\n",
      "Requirement already satisfied: pandas>=0.23.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from geopandas->up42-py) (1.2.4)\n",
      "Requirement already satisfied: python-dateutil>=2.7.3 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pandas>=0.23.0->geopandas->up42-py) (2.8.1)\n",
      "Requirement already satisfied: pytz>=2017.3 in c:\\users\\user\\anaconda3\\lib\\site-packages (from pandas>=0.23.0->geopandas->up42-py) (2021.1)\n",
      "Requirement already satisfied: certifi in c:\\users\\user\\anaconda3\\lib\\site-packages (from pyproj>=2.2.0->geopandas->up42-py) (2021.10.8)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\user\\anaconda3\\lib\\site-packages (from python-dateutil>=2.7.3->pandas>=0.23.0->geopandas->up42-py) (1.15.0)\n",
      "Collecting cligj>=0.4\n",
      "  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)\n",
      "Collecting click-plugins\n",
      "  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)\n",
      "Collecting munch\n",
      "  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)\n",
      "Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\\users\\user\\anaconda3\\lib\\site-packages (from matplotlib->up42-py) (2.4.7)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\user\\anaconda3\\lib\\site-packages (from matplotlib->up42-py) (0.10.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from matplotlib->up42-py) (1.3.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from matplotlib->up42-py) (9.0.1)\n",
      "Collecting affine\n",
      "  Downloading affine-2.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Collecting snuggs\n",
      "  Downloading snuggs-1.4.7-py3-none-any.whl (5.4 kB)\n",
      "Requirement already satisfied: chardet<5,>=3.0.2 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests->up42-py) (4.0.0)\n",
      "Requirement already satisfied: idna<3,>=2.5 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests->up42-py) (2.10)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests->up42-py) (1.26.4)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\user\\anaconda3\\lib\\site-packages (from requests-oauthlib->up42-py) (3.1.1)\n",
      "Building wheels for collected packages: fiona, rasterio\n",
      "  Building wheel for fiona (setup.py): started\n",
      "  Building wheel for fiona (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for fiona\n",
      "  Building wheel for rasterio (setup.py): started\n",
      "  Building wheel for rasterio (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for rasterio\n",
      "Failed to build fiona rasterio\n",
      "Installing collected packages: munch, cligj, click-plugins, snuggs, shapely, pyproj, fiona, branca, affine, rasterio, geopandas, geojson, folium, descartes, up42-py\n",
      "    Running setup.py install for fiona: started\n",
      "    Running setup.py install for fiona: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1a/6d/ee8b15e0d45dd7e9e7f2559e37f91915a19155cf8403948ff2082903ee30/rasterio-1.1.0.tar.gz#sha256=77aa68860da9d9382cee0294b78809b04ad4f884ea95d1dec084f2f9bab105e8 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_3h50b5d' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmplttur9_p'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_5583cd8a6ffc438a83e531986f0f50f0\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/f7/03/1dcc14b0c77ec4c4ca4bd917527bc41fdbba49f56015d535f3d781c826aa/rasterio-1.0.28.tar.gz#sha256=9def7698e7076c8f148e8bfa0b2a3334308b2f5311abe9e40269e0bf9dfc645d (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmplttur9_p' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_hi90g5i'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_b6a8e9f4adf146c2aa2987c1e53ea1d9\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ac/d9/c369236ff112376a298bbd615471b6786e8974656c66e9db679f432f8932/rasterio-1.0.27.tar.gz#sha256=403d2c80cddd6395f3fe5474f43333415dc0dcf430d861de82234988d20d6147 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp_hi90g5i' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpj5ma1vm8'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_32287b484f814573a2778720be82ba73\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/30/7c/c66b72339b17dfb58f2260473b575ed875216c4de8f579883ef3690b8759/rasterio-1.0.26.tar.gz#sha256=9d5246631b2295b9fb417f220d009a1954aeb5895c9e27bab71fc143f4ba5633 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpj5ma1vm8' Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpqhvmp60p'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_c217899e34fc4b1390c9feb0edaef4e9\n",
      "  Complete output (2 lines):\n",
      "  INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "  ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/0c/62/91d23e91e7c2b6db1ba208c1e1ced59554a0e651087bf0a854d915f08d10/rasterio-1.0.25.tar.gz#sha256=f821efe923098bd9b1792553a9f5282f6aefdb8fa638e7d966dbcdc50b6b0333 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' 'C:\\Users\\User\\anaconda3\\lib\\site-packages\\pip\\_vendor\\pep517\\_in_process.py' get_requires_for_build_wheel 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpqhvmp60p' Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ce80425b44134f2ba662c9769a4b2406\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ce80425b44134f2ba662c9769a4b2406\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-j6k7b5nn'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_ce80425b44134f2ba662c9769a4b2406\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/57/84/be5689470a73f5f8988cf44b81cb3493ebb8abbbebb69768c8fc86fccdd5/rasterio-1.0.24.tar.gz#sha256=4839479621045211f66868ec49625979693450bc2e476f23e7e8ac4804eaf452 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_4099ca4de80d4871a5fad76395881f49\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_4099ca4de80d4871a5fad76395881f49\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-m4ge_kj3'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_4099ca4de80d4871a5fad76395881f49\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/46/ee/f9b4bfb55b6cf1b5562e0b16bc75ab2ca3810587753e4c9944279d75540c/rasterio-1.0.23.tar.gz#sha256=45e1a4b3c5c58a0b9f1a6bfd0aa08bdc15da57fa690a1f6f26d1a6a3d3cc7aa5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_227b426f10d34890b8311e417277898e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_227b426f10d34890b8311e417277898e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-k6va4sa_'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_227b426f10d34890b8311e417277898e\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ce/90/8af39cdfed9a40bd59801f101f74eab5f1562d3557806ddfa2ed86d4be0b/rasterio-1.0.22.tar.gz#sha256=31c68b1ed8684ccc4855daeb9fe6c42bf5d54bbade8f2ab225370b7169422d7d (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c11e55d351f041c497070232da03a103\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c11e55d351f041c497070232da03a103\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-mo6l4fj1'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_c11e55d351f041c497070232da03a103\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/b4/0f/c5a412208f217bba892e5482c1129df29bdfe474a069aba36407ee68c518/rasterio-1.0.21.tar.gz#sha256=5dbe570d381e6bec0da703a92ebf543ca01d9b34ac6ad5f3791fdf0a7aab27a3 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_1d57db93ff204626a9f0da8e076f6b8f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_1d57db93ff204626a9f0da8e076f6b8f\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-sd2f9ug4'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_1d57db93ff204626a9f0da8e076f6b8f\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/75/88/1abc8a5128a66790d7e99ec3a6139d41ffd8f4fb0471218cfa3ce4e5ce4b/rasterio-1.0.20.tar.gz#sha256=820799cfd650d1518b52da9058a89a8d5452743d7593f3a57eab267b6a63b341 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_3c91081de4284bf983590fdb9929fa10\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_3c91081de4284bf983590fdb9929fa10\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-0rcz4czj'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_3c91081de4284bf983590fdb9929fa10\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/4e/79/b3e2d1783cde76d31eb87fa859eadf6855743d18c52942fbaa5f638e98a9/rasterio-1.0.18.tar.gz#sha256=02eabc24a2e1e323ebda385c608183a66ab56e46ff2077ac2aecd0f6ac3c3ea5 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_dd920b4fb6f242d6a27e87898f939cd5\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_dd920b4fb6f242d6a27e87898f939cd5\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-kxqx9uh4'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_dd920b4fb6f242d6a27e87898f939cd5\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/23/40/6bf2f3e50e5e89a6c2efad33e3409a0133129aa8bba66a4540dc0912f807/rasterio-1.0.17.tar.gz#sha256=0f346fdfb65ef166e640f19a25fdceb834c49091e4141b5e613a8b90d3a8ad80 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c240f40f133546f9871f08f7800b4a4f\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c240f40f133546f9871f08f7800b4a4f\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-ivjf5nf4'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_c240f40f133546f9871f08f7800b4a4f\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ee/81/29b30295af0cd7fddb3a0c4b2fc6c57ac0571e1d33c88c340e8cd53da25b/rasterio-1.0.16.tar.gz#sha256=8010425eb7804cfa3785ae2f59ddcd9f8de51d03516719d084e84e80c89ee955 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_d668d2224b0047bbb65adb1ed1b6a5af\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_d668d2224b0047bbb65adb1ed1b6a5af\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-93fenuf_'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_d668d2224b0047bbb65adb1ed1b6a5af\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/f3/7a/c9ea37324b40e04875aa776350bd3671add21fa64eceef0e552bd9697c20/rasterio-1.0.15.tar.gz#sha256=d35a9849d4947f7dc75f25024cad034f3cd7275d72a7d37a7c3376e01371a3ce (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_44d95309ccad493eac5d205a84b24467\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_44d95309ccad493eac5d205a84b24467\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-8p36md05'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_44d95309ccad493eac5d205a84b24467\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/14/f9/f6cdd44ddb8d390ebab7d0b2f9e4180a9cd605d28d093b0307c7ec312baa/rasterio-1.0.14.tar.gz#sha256=c63cfd18d1b26322371dc193bfff93dbb035a3f89b65d9675b424fd7dd57b881 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_28b34070375d47448fa9ed73e2e2ad5e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_28b34070375d47448fa9ed73e2e2ad5e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-jwywubo2'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_28b34070375d47448fa9ed73e2e2ad5e\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/d1/da/5ccbaed45770f37520f8ae97c5e16f507b92a3951a3c40eea46fbfae731a/rasterio-1.0.13.tar.gz#sha256=812c54ba444a9a7967bfd73256a058d6dd8cdfa810145fe44320eb5b5dfc9c48 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_eb070c8d51d34a8296f31d9a3f879605\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_eb070c8d51d34a8296f31d9a3f879605\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-d1bvt74_'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_eb070c8d51d34a8296f31d9a3f879605\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9d/06/5f65bc41b119e7e68ff3a1dae8e285a9be37d9360550e275bde537a55399/rasterio-1.0.12.tar.gz#sha256=b01976bbadb8382573577b67b75b653cee1fec634f23a321e52dccaed53757e6 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_0ab0688f74194341a468cb2f02dae73e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_0ab0688f74194341a468cb2f02dae73e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-g_3ppdn5'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_0ab0688f74194341a468cb2f02dae73e\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/32/2f/75727c18e8de01aa67871f607af8aa8a9bfc57f6ca6a758c96ec774bcb72/rasterio-1.0.11.tar.gz#sha256=7064460314ea289f753bb6e48684a8537f3f6aa421ae9a785dc55d9926c6c9da (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_0c42fe724f6643aa8d88e53d639b7afb\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_0c42fe724f6643aa8d88e53d639b7afb\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-wspmsvkm'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_0c42fe724f6643aa8d88e53d639b7afb\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/86/0a/a4ef029e5d2b3fc3a0c9c8846e44ee35797d814ff4ab3cd0ac76fc002584/rasterio-1.0.10.tar.gz#sha256=26933c002ad5084b3b394136dec94d36f586b29564d9ee21817b7b5d073bc190 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_1cae55a7c1e04796a642c2ce5da450bf\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_1cae55a7c1e04796a642c2ce5da450bf\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-7_4an722'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_1cae55a7c1e04796a642c2ce5da450bf\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/e9/1e/e42550364e3472f10503586d2f76d740640c0b2d983b66280ec011ece03d/rasterio-1.0.9.tar.gz#sha256=8f6905bb1f0b5674f7eb289761d57fb24bd9471a994e0cc235963389eaa2cf9f (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_58dfa0bb48ba40c8abb52a0f583a6e30\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_58dfa0bb48ba40c8abb52a0f583a6e30\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-jlffuro7'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_58dfa0bb48ba40c8abb52a0f583a6e30\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1a/d5/6cad936ff9beb89e79b1dae946f3097c70f7ab71cda5a9e356aec2e9ce9b/rasterio-1.0.8.tar.gz#sha256=fd0c821f0dbf0cbba88cb394ee9f2bfa60677730381e356caaec1672c50e8dc0 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_d26cc94654084dfbadb67d67e89e097b\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_d26cc94654084dfbadb67d67e89e097b\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-k_k975id'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_d26cc94654084dfbadb67d67e89e097b\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ce/e3/86ef71d178887f2e365763607f974d5a70be9fbd422e4378bd8c16b8c306/rasterio-1.0.7.tar.gz#sha256=707ddebceb76a9bf0b7ac81b937370fd5eb0943342955941e636ca294cd1a60a (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_19bce05c308745d5b907fe34a0739117\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_19bce05c308745d5b907fe34a0739117\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-emoay0ak'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_19bce05c308745d5b907fe34a0739117\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/fd/2d/e24fc955d9b8dbf152cc1f019267688324409ec27d17014f1a7adfa195af/rasterio-1.0.6.tar.gz#sha256=b3c6a10f17cc8477b677f4e3743684f6591d67cb289c3f676f8850c9bf0de564 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_856246171e74482491acbbaec12cf558\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_856246171e74482491acbbaec12cf558\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-f2o112zk'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_856246171e74482491acbbaec12cf558\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/8f/06/78d85a7a1a44b5cee5aaae62692a7cec0a94af09e827db9f753b4ff990a3/rasterio-1.0.5.tar.gz#sha256=530bc3018ccb66e0dd4d408a9f39566c43bac9768b68cde31fa24333c3d56685 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ba68e64dcc194e4ab87f68973be2f083\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ba68e64dcc194e4ab87f68973be2f083\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-msw5sv33'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_ba68e64dcc194e4ab87f68973be2f083\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/66/f3/0a4f444d239896b3f7d60b205ba05d02fec62bc7ea8598f630f1d5a45ca4/rasterio-1.0.4.tar.gz#sha256=ed018f8c64b06cca0e9a89967862f6898be2cf91038fcff7a7ae598b18f194a7 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_a8d3d2f18ab9484ab510d108b929dbc3\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_a8d3d2f18ab9484ab510d108b929dbc3\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-rqutpyz2'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_a8d3d2f18ab9484ab510d108b929dbc3\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/a6/70/9ccbc9aac78db96c7b9291515ec3676ff2da6a746a0bd826bc84b3115a7b/rasterio-1.0.3.post1.tar.gz#sha256=949cd9ce0143e3e71171e5833c98713cb2fbda1e64aaf27d9e795ac8225a6319 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c861ded1da19443db967b2e8de9f8f5e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_c861ded1da19443db967b2e8de9f8f5e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-dx6zcv7a'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_c861ded1da19443db967b2e8de9f8f5e\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/e1/b3/e34a28e3243454d179fd085ec9f933fb2b879023c488479875c39f01ad43/rasterio-1.0.3.tar.gz#sha256=8fb24254f5296ab9468f578dd4c07783fda151f86e3f917e8b97fb1e2c02721c (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_6f426d31c66b48c9bed0fa4fe89075f4\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_6f426d31c66b48c9bed0fa4fe89075f4\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-s79t_1_a'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_6f426d31c66b48c9bed0fa4fe89075f4\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/7f/43/fb81ba30ddd3ba7cc6d381f4af35504cfd7ad7f1d46041850d03fc626c6a/rasterio-1.0.2.tar.gz#sha256=335eced9009852ce13517a88d4e05427c3fbda5f865e902e678612e2ab63b590 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_9fad51109285418f950329e0df176141\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_9fad51109285418f950329e0df176141\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-oo4jcc9s'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_9fad51109285418f950329e0df176141\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ef/e2/eea3c9fd760b2fd3c68152e287e18698a11997ca265bbcbde999c13f1521/rasterio-1.0.1.tar.gz#sha256=b96be3e541f9f7b672eaa7b41bbe68216b5dea3dc7bcd96ef00db3c2a9553b15 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ad777aa2356d46fe80f6fdf68e401327\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_ad777aa2356d46fe80f6fdf68e401327\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-cpozoat7'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_ad777aa2356d46fe80f6fdf68e401327\\\n",
      "    Complete output (2 lines):\n",
      "    INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.\n",
      "    ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/33/22/ad2ea27c9829582ab5280f35cc61e424970ce0add34e258c9e171a62cb73/rasterio-1.0.0.tar.gz#sha256=6f2e90f2b740d727b36e39550e2a949d52551717812f9b4748f9bc351d666274 (from https://pypi.org/simple/rasterio/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_94023f8bf03440c29c6a618c34b12d9a\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_94023f8bf03440c29c6a618c34b12d9a\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-o83m5bw4'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_94023f8bf03440c29c6a618c34b12d9a\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/67/5c/4e028e84a1f0cb3f8a994217cf2366360ca984dfc1433f6171de527d0dca/Fiona-1.8.21.tar.gz#sha256=3a0edca2a7a070db405d71187214a43d2333a57b4097544a3fcc282066a58bfc (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_ef40dce09fe7466ab5353e25f7a6e3a5\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_ef40dce09fe7466ab5353e25f7a6e3a5\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-6pvrcl_q'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_ef40dce09fe7466ab5353e25f7a6e3a5\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ec/f7/093890341a7e8fbfcdfa04caf4dfb588ebab32c13ceaa6a3819da79ea106/Fiona-1.8.20.tar.gz#sha256=a70502d2857b82f749c09cb0dea3726787747933a2a1599b5ab787d74e3c143b (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_2620cda053c140d9979d2e2591d4e84d\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_2620cda053c140d9979d2e2591d4e84d\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-lcci49pz'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_2620cda053c140d9979d2e2591d4e84d\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/a0/d9/6042aeb073d11341f7726de0586ff71c13117c34959dcf07bd4ee6d4b93e/Fiona-1.8.19.tar.gz#sha256=b9059e0b29c2e9e6b817e53f941e77e1aca7075f986005d38db307067b60458f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_0785c9bb544448eab959291d042267ec\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_0785c9bb544448eab959291d042267ec\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-a3g_485l'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_0785c9bb544448eab959291d042267ec\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9f/e8/401cdaa58d862a25c4b3365acf7d2bd7ac77191e3dc9acdcdac0eff20ff0/Fiona-1.8.18.tar.gz#sha256=b732ece0ff8886a29c439723a3e1fc382718804bb057519d537a81308854967a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_3286da5adde9464fab498ea707fbb3d7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_3286da5adde9464fab498ea707fbb3d7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-phkvklc2'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_3286da5adde9464fab498ea707fbb3d7\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/88/62/69347ba2c41b526e1953c4cb66d51170b2869808863c03af202ba0121670/Fiona-1.8.17.tar.gz#sha256=716201c21246587f374785bec6d6a20a984fe1f6c2b0e83bf15127eb8f724d0c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_28076d262fcf4c8298d478f68d52483e\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_28076d262fcf4c8298d478f68d52483e\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-1y4gd74k'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_28076d262fcf4c8298d478f68d52483e\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/1e/60/dfc6115a11338d8aa96cacd8c60635223d9c97d61d556c90acc5dfd663fa/Fiona-1.8.16.tar.gz#sha256=fd6dfb65959becc916e9f6928618bfd59c16cdbc413ece0fbac61489cd11255f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_8ea9ea3bc4da4847b8066b9170e4aee9\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_8ea9ea3bc4da4847b8066b9170e4aee9\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-zxgase9s'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_8ea9ea3bc4da4847b8066b9170e4aee9\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/55/2f/17450ec2c8fcc720a8a3e4d9a383499508475c7cfb90f7eca9fb585ac598/Fiona-1.8.15.tar.gz#sha256=3b1c9b5c834fae2fe947cfaea176db890bc6750d1a6ba9f54d969c19ffcd191e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_384fb931e96345209cd1670790cc3954\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_384fb931e96345209cd1670790cc3954\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-y0j_sw4b'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_384fb931e96345209cd1670790cc3954\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/5c/fd/5ec54f2d9b3d5dd23dd443fad5630d6b872e2664814c68b856c47e0d65af/Fiona-1.8.14.tar.gz#sha256=6eac038206c89d2cf5f99ea38b81cc228dc21eac5f47870a9a32d453b0007f4d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_b78e224d472d45eb80d065fda0089dba\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_b78e224d472d45eb80d065fda0089dba\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-egio4l9p'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_b78e224d472d45eb80d065fda0089dba\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/6d/42/f4a7cac53b28fa70e9a93d0e89a24d33e14826dad6644b699362ad84dde0/Fiona-1.8.13.post1.tar.gz#sha256=1a432bf9fd56f089256c010da009c90d4a795c531a848132c965052185336600 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_f3b6d2060f3d4edbb76514d27c34498b\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_f3b6d2060f3d4edbb76514d27c34498b\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-5t43knax'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_f3b6d2060f3d4edbb76514d27c34498b\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/be/04/31d0a6f03943b1684f32c9b861be40c1fd282468fa6bd54ddf4a774e6b0f/Fiona-1.8.13.tar.gz#sha256=5ec34898c8b983a723fb4e949dd3e0ed7e691c303e51f6bfd61e52ac9ac813ae (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_337dcd2c09914dd5bfa7d1d8a7584618\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_337dcd2c09914dd5bfa7d1d8a7584618\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-1wwa5d2o'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_337dcd2c09914dd5bfa7d1d8a7584618\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/97/d8/feab39987296437fbdc3029fb39752a14355d217d73b93471010b8dd63a3/Fiona-1.8.12.tar.gz#sha256=c9266ddf6ae2a64fcea20014ddf27f800ac07584f2fdb09c2a02f3b3a52e371c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_2fdca93a3f4541c284b8a003740f3e80\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_2fdca93a3f4541c284b8a003740f3e80\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-kznyxo14'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_2fdca93a3f4541c284b8a003740f3e80\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9d/f4/0a0ddc6174c4a93679b5f1dd3535e7ef8989828e6d5f86112de681f8c87b/Fiona-1.8.11.tar.gz#sha256=1e7ca9e051f5bffa1c43c70d573da9ca223fc076b84fa73380614fc02b9eb7f6 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_1eeaf135f67b421dac50a31587307266\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_1eeaf135f67b421dac50a31587307266\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-6y5f7ve_'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_1eeaf135f67b421dac50a31587307266\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/13/73/f80b491ed8559326fab202a6d6333a3cd6e8be1e9d782bc6c0d03d476457/Fiona-1.8.10.tar.gz#sha256=ff562eb2f3960e21f8c7f050ddd7f47a763869ea14afc2234a40df72666c6a2c (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_835e75fbaf79408fa9d7ea129bc1e869\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_835e75fbaf79408fa9d7ea129bc1e869\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-kbpe879x'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_835e75fbaf79408fa9d7ea129bc1e869\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/9b/52/45e75507660ce0e86176d0f59b659560f687e2c7e9ebf82a10e7dcd2d3b7/Fiona-1.8.9.post2.tar.gz#sha256=210fb038b579fab38f35ddbdd31b9725f4d5099b3edfd4b87c983e5d47b79983 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_d68188a8e0d54747a99e3518babe1320\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_d68188a8e0d54747a99e3518babe1320\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-pkk5euw1'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_d68188a8e0d54747a99e3518babe1320\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/0e/a4/d9dd7399be809d3990f5000fb6ae43189ea26ae88be1bed3a4c9ddc1becc/Fiona-1.8.9.post1.tar.gz#sha256=d5e0ea0b8addffe9cba4cb59e2bd495b015230e7a1b1597974f5048211930199 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_a4655571a9e6430ebb5ae9d50d03d11d\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_a4655571a9e6430ebb5ae9d50d03d11d\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-lfh4vmk8'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_a4655571a9e6430ebb5ae9d50d03d11d\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/ad/92/dcbd8c54d697c22f299b5af63b6df3acfbd06c6d72e249614c05be99337c/Fiona-1.8.9.tar.gz#sha256=4dd6e2f5327c1174143c7c8594a75d373bc72f2c9a2a6daee312c3186a128add (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_eff7493db6c54398a9d04f6d4795661d\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_eff7493db6c54398a9d04f6d4795661d\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-ajh1e7o9'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_eff7493db6c54398a9d04f6d4795661d\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/94/7f/e288db1ad63d759d494c30caae34f865e0c6927588c490705e91b7134193/Fiona-1.8.8.tar.gz#sha256=711c3be73203b37812992089445a1e4e9d3d6b64e667389f7b15406e15a91e83 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_09a346d377984559ba32048a9c6aa455\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_09a346d377984559ba32048a9c6aa455\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-xqqlpd2c'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_09a346d377984559ba32048a9c6aa455\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/78/62/daafd070aebefa639df247705b97f13f7cfad43895581b5cae41bd886709/Fiona-1.8.7.tar.gz#sha256=a55a23615bad3e142d4e4cda97bb5de83c778a80049222e9dffae93c13b5cf93 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_e8e26d04f71140be82b6368676f578ec\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_e8e26d04f71140be82b6368676f578ec\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-n7d77514'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_e8e26d04f71140be82b6368676f578ec\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/41/9d/63696e7b1de42aad294d4781199a408bec593d8fdb80a2b4a788c911a33b/Fiona-1.8.6.tar.gz#sha256=fa31dfe8855b9cd0b128b47a4df558f1b8eda90d2181bff1dd9854e5556efb3e (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_3c1be19f328543958cf09da33045b043\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_3c1be19f328543958cf09da33045b043\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-45z77eee'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_3c1be19f328543958cf09da33045b043\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/7b/af/1c2c83c4a8363a4ce9fea817b1910b5e071bed012e18257faa2a0ab3cfe7/Fiona-1.8.5.tar.gz#sha256=4f5cc2d449edbbf693c83e24cdada72de7c41297383d16fcc92387eb445e9d35 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_23b421745b6f446bb5e4045c45c45138\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_23b421745b6f446bb5e4045c45c45138\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-2dxbfhoz'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_23b421745b6f446bb5e4045c45c45138\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/3a/16/84960540e9fce61d767fd2f0f1d95f4c63e99ab5d8fddc308e8b51b059b8/Fiona-1.8.4.tar.gz#sha256=aec9ab2e3513c9503ec123b1a8573bee55fc6a66e2ac07088c3376bf6738a424 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_8e8e3bd2d653491d93fe7553c15640c4\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_8e8e3bd2d653491d93fe7553c15640c4\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-7vpe20hl'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_8e8e3bd2d653491d93fe7553c15640c4\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/46/d1/fcdb32513a03abfde0d97fd9782ce0f8cc0540fa6c6ce783e87b94064964/Fiona-1.8.3.tar.gz#sha256=3e831100a23c3b6cd32b98baf0c9e2119d909b44a5cf4533d3625f61dcf2d2b1 (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_28b526563e9846bebbde397fe1f8a064\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_28b526563e9846bebbde397fe1f8a064\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-7kb_srby'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_28b526563e9846bebbde397fe1f8a064\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/25/50/0466d5d83e1859c5ca38351ee932d64cc5635f9d4dad522879e58f4b0018/Fiona-1.8.2.tar.gz#sha256=4c6419b7ac29136708029f6a44b4ccd458735a4d241016c7b1bab41685c08d8f (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_fe326c6ccfb1413392b48a8dc26b80d7\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_fe326c6ccfb1413392b48a8dc26b80d7\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-nogih3iw'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_fe326c6ccfb1413392b48a8dc26b80d7\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/3e/5f/0c6704efeea2ff3fba7f54cc6ec38070157f21bc1cffa7bdfa7c9f6b8f7a/Fiona-1.8.1.tar.gz#sha256=4c34bb4c5cd788aaf14e5484c3b7de407b1a8a7c7b2d29bbb2e8b37931e83b8d (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_a0fdfb732f1b49b1988e38526c4ed127\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_a0fdfb732f1b49b1988e38526c4ed127\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-lg5h7mxv'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_a0fdfb732f1b49b1988e38526c4ed127\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "WARNING: Discarding https://files.pythonhosted.org/packages/2a/bd/c1efc2680f338e5941121c776d6323af6b9698ac739e22ba523cee348a7f/Fiona-1.8.0.tar.gz#sha256=20141a9ece06daa7bb4333fba640c2fe39a49f8aca5492d1da8595d41e91844a (from https://pypi.org/simple/fiona/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-wheel-c252vpjv'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\n",
      "  Complete output (48 lines):\n",
      "  C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'\n",
      "    warnings.warn(msg)\n",
      "  C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'\n",
      "    warnings.warn(msg)\n",
      "  C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'requires_external'\n",
      "    warnings.warn(msg)\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.8\n",
      "  creating build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\collection.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\compat.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\crs.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\drvsupport.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\errors.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\inspector.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\rfc3339.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\tool.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\transform.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  copying .\\fiona\\__init__.py -> build\\lib.win-amd64-3.8\\fiona\n",
      "  creating build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\bounds.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\calc.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\cat.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\collect.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\distrib.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\dump.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\env.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\filter.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\helpers.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\info.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\insp.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\load.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\ls.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\main.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\options.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  copying .\\fiona\\fio\\__init__.py -> build\\lib.win-amd64-3.8\\fiona\\fio\n",
      "  running build_ext\n",
      "  building 'fiona._transform' extension\n",
      "  creating build\\temp.win-amd64-3.8\n",
      "  creating build\\temp.win-amd64-3.8\\Release\n",
      "  creating build\\temp.win-amd64-3.8\\Release\\fiona\n",
      "  C:\\Users\\User\\anaconda3\\Library\\mingw-w64\\bin\\gcc.exe -mdll -O -Wall -DMS_WIN64 -DMS_WIN64=1 -IC:\\Users\\User\\anaconda3\\include -IC:\\Users\\User\\anaconda3\\include -c fiona/_transform.cpp -o build\\temp.win-amd64-3.8\\Release\\fiona\\_transform.o\n",
      "  fiona/_transform.cpp:606:22: fatal error: cpl_conv.h: No such file or directory\n",
      "  compilation terminated.\n",
      "  error: command 'C:\\\\Users\\\\User\\\\anaconda3\\\\Library\\\\mingw-w64\\\\bin\\\\gcc.exe' failed with exit status 1\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for fiona\n",
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\Users\\User\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_b0e62f737f214632a113e9049c29c379\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\rasterio_b0e62f737f214632a113e9049c29c379\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-wheel-wwpqfv7g'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\rasterio_b0e62f737f214632a113e9049c29c379\\\n",
      "  Complete output (69 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.8\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\compat.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\coords.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\crs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\dtypes.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\enums.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\errors.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\features.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\fill.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\plot.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\profiles.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\tool.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\vfs.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\windows.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  copying .\\rasterio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\bounds.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\calc.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\clip.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\convert.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\edit_info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\env.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\helpers.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\info.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\insp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\main.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\options.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\overview.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\rasterize.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\sample.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\shapes.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\stack.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\transform.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\warp.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  copying .\\rasterio\\rio\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\rio\n",
      "  creating build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\mask.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\merge.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  copying .\\rasterio\\tools\\__init__.py -> build\\lib.win-amd64-3.8\\rasterio\\tools\n",
      "  running egg_info\n",
      "  writing rasterio.egg-info\\PKG-INFO\n",
      "  writing dependency_links to rasterio.egg-info\\dependency_links.txt\n",
      "  writing entry points to rasterio.egg-info\\entry_points.txt\n",
      "  writing requirements to rasterio.egg-info\\requires.txt\n",
      "  writing top-level names to rasterio.egg-info\\top_level.txt\n",
      "  reading manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "  writing manifest file 'rasterio.egg-info\\SOURCES.txt'\n",
      "  running build_ext\n",
      "  building 'rasterio._base' extension\n",
      "  creating build\\temp.win-amd64-3.8\n",
      "  creating build\\temp.win-amd64-3.8\\Release\n",
      "  creating build\\temp.win-amd64-3.8\\Release\\rasterio\n",
      "  C:\\Users\\User\\anaconda3\\Library\\mingw-w64\\bin\\gcc.exe -mdll -O -Wall -DMS_WIN64 -DMS_WIN64=1 -IC:\\Users\\User\\anaconda3\\lib\\site-packages\\numpy\\core\\include -IC:\\Users\\User\\anaconda3\\include -IC:\\Users\\User\\anaconda3\\include -c rasterio/_base.c -o build\\temp.win-amd64-3.8\\Release\\rasterio\\_base.o\n",
      "  rasterio/_base.c:287:22: fatal error: cpl_conv.h: No such file or directory\n",
      "  compilation terminated.\n",
      "  error: command 'C:\\\\Users\\\\User\\\\anaconda3\\\\Library\\\\mingw-w64\\\\bin\\\\gcc.exe' failed with exit status 1\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for rasterio\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\Users\\User\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-record-gz1_za8m\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\User\\anaconda3\\Include\\fiona'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-i_uok352\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\n",
      "    Complete output (18 lines):\n",
      "    C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'metadata_version'\n",
      "      warnings.warn(msg)\n",
      "    C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'requires_python'\n",
      "      warnings.warn(msg)\n",
      "    C:\\Users\\User\\anaconda3\\lib\\distutils\\dist.py:274: UserWarning: Unknown distribution option: 'requires_external'\n",
      "      warnings.warn(msg)\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    running build_ext\n",
      "    building 'fiona._transform' extension\n",
      "    creating build\\temp.win-amd64-3.8\n",
      "    creating build\\temp.win-amd64-3.8\\Release\n",
      "    creating build\\temp.win-amd64-3.8\\Release\\fiona\n",
      "    C:\\Users\\User\\anaconda3\\Library\\mingw-w64\\bin\\gcc.exe -mdll -O -Wall -DMS_WIN64 -DMS_WIN64=1 -IC:\\Users\\User\\anaconda3\\include -IC:\\Users\\User\\anaconda3\\include -c fiona/_transform.cpp -o build\\temp.win-amd64-3.8\\Release\\fiona\\_transform.o\n",
      "    fiona/_transform.cpp:606:22: fatal error: cpl_conv.h: No such file or directory\n",
      "    compilation terminated.\n",
      "    error: command 'C:\\\\Users\\\\User\\\\anaconda3\\\\Library\\\\mingw-w64\\\\bin\\\\gcc.exe' failed with exit status 1\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\Users\\User\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-i_uok352\\\\fiona_59cb794a6d7047bfb0f902a19e65cd39\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-record-gz1_za8m\\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\\Users\\User\\anaconda3\\Include\\fiona' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "pip install up42-py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "621200db",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'up42'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-a2589dc846c1>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mup42\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'up42'"
     ]
    }
   ],
   "source": [
    "import up42"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
